### PR TITLE
Package the aps_cycle_info.yml file

### LINKED ISSUE #734: Still missing YML files
> tried the same steps as yesterday on our call with the 1.6.6rc1, and get the same error: https://gist.github.com/canismarko/90200e083b1663b03c51ea129c2ce052

_Originally posted by @canismarko in https://github.com/BCDA-APS/apstools/issues/732#issuecomment-1277738238_

- #733
- #732

### PR DESCRIPTION
**Pull request by prjemian**
- close #734

@canismarko I'll make a 1.6.7rc1 tag we can check.  Might take an hour to get it available.  First by pip, then by conda.

### CODE REVIEW

**Comment by prjemian** [comment]
@canismarko: [pip](https://pypi.org/project/apstools/1.6.7rc1/#modal-close) version is ready, conda version is in the publishing queue.  Watch [here](https://anaconda.org/conda-forge/apstools/files) for the new version.  Usually takes 10 minutes - 2 hours, depending on the conda-forge queue length.

**Comment by prjemian** [comment]
Here's my test of the pip package:

```bash
(base) prjemian@zap:~/Downloads$ wget https://files.pythonhosted.org/packages/2b/19/57ad070e0120f8a83b91b772f49218c52226d263c06536f241b42428896d/apstools-1.6.7rc1.tar.gz
--2022-10-13 17:20:51--  https://files.pythonhosted.org/packages/2b/19/57ad070e0120f8a83b91b772f49218c52226d263c06536f241b42428896d/apstools-1.6.7rc1.tar.gz
Resolving files.pythonhosted.org (files.pythonhosted.org)... 146.75.81.63, 2a04:4e42:83::319
Connecting to files.pythonhosted.org (files.pythonhosted.org)|146.75.81.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 640301 (625K) [application/x-tar]
Saving to: ‘apstools-1.6.7rc1.tar.gz’

apstools-1.6.7rc1.tar.gz              100%[=======================================================================>] 625.29K  --.-KB/s    in 0.05s   

2022-10-13 17:20:52 (11.3 MB/s) - ‘apstools-1.6.7rc1.tar.gz’ saved [640301/640301]

(base) prjemian@zap:~/Downloads$ tar tzf ./apstools-1.6.7rc1.tar.gz | grep aps_cycle_info
apstools-1.6.7rc1/apstools/devices/aps_cycle_info.yml
```

It's there.

**Comment by prjemian** [comment]
Here's my test of the conda package:

```bash
wget https://anaconda.org/conda-forge/apstools/1.6.7rc1/download/noarch/apstools-1.6.7rc1-pyhd8ed1ab_0.tar.bz2
tar tjf ./apstools-1.6.7rc1-pyhd8ed1ab_0.tar.bz2 | grep aps_cycle_info
```

It's not there.  More work for conda packaging.

**Comment by prjemian** [comment]
After pip install on the _clean_ workstation, it's not there:

```bash
(test) prjemian@sus:~/Downloads$ python -c "import apstools, pathlib; path=pathlib.Path(apstools.__file__).parent / 'devices' / 'aps_cycle_info.yml'; print(path.exists())"
False
```

**Comment by prjemian** [comment]
It's not obvious what packaging process is failing us here.  Some details are escaping us now.  Perhaps it is time to refactor to the previous method, using python-versioneer and not setuptools-scm.

**Comment by prjemian** [comment]
@canismarko If 1.6.7rc2 works for you, please review & approve this PR.

**Comment by prjemian** [comment]
@gfabbris If 1.6.7rc2 works for you, please review & approve this PR.

**Comment by prjemian** [comment]
Discovered a new pin on databroker=1.2.5, it fails with 1.2.4 as shown:

```bash
(test) prjemian@opp:~$ python
Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:38:57) [GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from apstools.devices import ApsCycleDM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/prjemian/micromamba/envs/test/lib/python3.10/site-packages/apstools/devices/__init__.py", line 49, in <module>
    from .kohzu_monochromator import KohzuSeqCtl_Monochromator
  File "/home/prjemian/micromamba/envs/test/lib/python3.10/site-packages/apstools/devices/kohzu_monochromator.py", line 20, in <module>
    from ..utils import run_in_thread
  File "/home/prjemian/micromamba/envs/test/lib/python3.10/site-packages/apstools/utils/__init__.py", line 1, in <module>
    from .catalog import copy_filtered_catalog
  File "/home/prjemian/micromamba/envs/test/lib/python3.10/site-packages/apstools/utils/catalog.py", line 19, in <module>
    import databroker._drivers.mongo_normalized
  File "/home/prjemian/micromamba/envs/test/lib/python3.10/site-packages/databroker/_drivers/mongo_normalized.py", line 10, in <module>
    from ..core import to_event_pages, to_datum_pages, Entry
  File "/home/prjemian/micromamba/envs/test/lib/python3.10/site-packages/databroker/core.py", line 27, in <module>
    from .intake_xarray_core.base import DataSourceMixin
  File "/home/prjemian/micromamba/envs/test/lib/python3.10/site-packages/databroker/intake_xarray_core/__init__.py", line 6, in <module>
    intake.register_driver('databroker-remote-xarray', RemoteXarray)
  File "/home/prjemian/micromamba/envs/test/lib/python3.10/site-packages/intake/source/discovery.py", line 116, in register_driver
    raise ValueError(f"Driver {name} already enabled")
ValueError: Driver databroker-remote-xarray already enabled
>>> exit()
(test) prjemian@opp:~$ micromamba list databroker
List of packages in environment: "/home/prjemian/micromamba/envs/test"

  Name             Version  Build         Channel    
───────────────────────────────────────────────────────
  databroker       1.2.4    pyhd8ed1ab_0  conda-forge
  databroker-pack  0.3.0    pyhd8ed1ab_0  conda-forge
(test) prjemian@opp:~$ micromamba install -c conda-forge databroker=1.2.5

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.10.*


Transaction

  Prefix: /home/prjemian/micromamba/envs/test

  Updating specs:

   - databroker=1.2.5


  Package       Version  Build         Channel                  Size
──────────────────────────────────────────────────────────────────────
  Upgrade:
──────────────────────────────────────────────────────────────────────

  - databroker    1.2.4  pyhd8ed1ab_0  conda-forge            Cached
  + databroker    1.2.5  pyhd8ed1ab_0  conda-forge/noarch      150kB

  Downgrade:
──────────────────────────────────────────────────────────────────────

  - intake        0.6.6  pyhd8ed1ab_0  conda-forge            Cached
  + intake        0.6.4  pyhd8ed1ab_0  conda-forge/noarch      113kB

  Summary:

  Upgrade: 1 packages
  Downgrade: 1 packages

  Total download: 263kB

──────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] y

Transaction starting
intake                                             113.0kB @ 352.0kB/s  0.3s
databroker                                         149.9kB @ 449.5kB/s  0.3s
Changing intake-0.6.6-pyhd8ed1ab_0 ==> intake-0.6.4-pyhd8ed1ab_0
Changing databroker-1.2.4-pyhd8ed1ab_0 ==> databroker-1.2.5-pyhd8ed1ab_0
Transaction finished
(test) prjemian@opp:~$ python
Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:38:57) [GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from apstools.devices import ApsCycleDM
>>> 
```

**Comment by prjemian** [comment]
The pin exists: https://github.com/BCDA-APS/apstools/blob/ff65613beafb7ad56fb74de7a6bc62548340f454/environment.yml#L14 https://github.com/BCDA-APS/apstools/blob/ff65613beafb7ad56fb74de7a6bc62548340f454/requirements.txt#L3 https://github.com/BCDA-APS/apstools/blob/ff65613beafb7ad56fb74de7a6bc62548340f454/setup.cfg#L89

But in the apstools-feedstock [meta.yaml](https://github.com/conda-forge/apstools-feedstock/blob/aba1e26db7e8e3cb21222405ca945fd80feefec4/recipe/meta.yaml#L34) file, it is 1.2, so that's a conda package thing:

```yaml
    - databroker =1.2
```


Confirmed this works with the pip-installed package:

```python
(test) prjemian@opp:~$ python
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from apstools.devices import ApsCycleDM
>>> c = ApsCycleDM(name="c")
>>> c
ApsCycleDM(name='c', value='2022-3', timestamp=1665776471.7834408)
>>> exit()
(test) prjemian@opp:~$ micromamba list apstools
List of packages in environment: "/home/prjemian/micromamba/envs/test"

(test) prjemian@opp:~$ pip list | grep apstools
apstools               1.6.7rc2
```

**Comment by prjemian** [comment]
@canismarko , @gfabbris : "apstools==1.6.7rc3" is ready for pip install, apstools=1.6.7rc3 is ready (or will be real soon) on conda-forge, please test and review here

**Comment by prjemian** [comment]
Still, a conda install of apstools installs latest apstools but databroker=1.2.4.  Investigating...

**Comment by prjemian** [comment]
The install anomaly is local; when installing the [`bluesky_2022_3`](https://github.com/BCDA-APS/use_bluesky/blob/main/install/environment_2022_3.yml) environment, databroker 1.2.5 is installed.

**Comment by gfabbris** [comment]
Installed `apstools=1.6.7rc3` in a fresh environment (`conda create -n apstools-test -c conda-forge apstools=1.6.7rc3`) at the beamline and it works fine.

**Review by gfabbris — APPROVED** [review]

**Comment by prjemian** [comment]
Great! Once we hear from @canismarco, then I'll finish this release
process, with 1.6.7.

**Comment by canismarko** [comment]
I tested it with mamba and pip, and for each with ``from apstools import devices`` and ``from apstools.devices.aps_undulator import ApsUndulator``. Everything seems to working fine now. With conda, I imported the devices with no error. With pip, I ran into missing dependencies:

- matplotlib
- psutil

psutil is first pulled in by utils/memory.py", line 11. And matplotlib is pulled in by bluesky's best effort callback. Pip installing "psutil" and "bluesky[plotting]" before pip install "apstools==1.6.7rc3" solved the dependencies, so maybe these need to be added to setup.cfg or wherever?

**Comment by prjemian** [comment]
@canismarko : 1.6.7rc4 just released (with changes in 3cf1be8) for pip and conda installation, please test again

**Comment by canismarko** [comment]
Both pip and conda-forge work now for me.

**Review by canismarko — APPROVED** [review]

**Comment by prjemian** [comment]
Thanks! I'll proceed with the final release.

**Pull request merged**
