### PR TITLE
Improve diagnostics & reporting of lineup2() plan

### LINKED ISSUE #1044: lineup2() plan needs better diagnostics, especially when it does not succeed
When using the `lineup2()` plan, users have reported that the plan appears to run successfully and print a report of the peak statistics.  Yet the motor has not been moved to the expected position after `lineup2()` finishes.  The only possible diagnostic is to supply a `signals_stats=obj` kwarg to the plan, then check that after the scan.

How does a user know if `lineup2()` has not succeeded?  What reason(s)?

### PR DESCRIPTION
**Pull request by prjemian**
- close #1044
@jilavsky : Thanks for the prompting on this!

### CODE REVIEW

**Comment by jilavsky** [comment]
That looks great, thank you

**Comment by prjemian** [comment]
### success=True

```py
Motor: 'motor'  Detector: 'noisy_det'
========== ====================
statistic  value               
========== ====================
n          19                  
centroid   -0.00604313560021479
x_at_max_y 0.07498907624123874 
fwhm       2.427762264595814   
variance   0.8626928293778106  
sigma      0.9288125910956475  
min_x      -3.0                
mean_x     0.9535573837387351  
max_x      4.90711476747747    
min_y      -0.08111386966031231
mean_y     0.29494471116616    
max_y      0.980899512651778   
success    True                
========== ====================
```

### success=False

```py
Motor: 'motor'  Detector: 'noisy_det'
========== ================================
statistic  value                          
========== ================================
n          19                             
centroid   -0.5391606368907506            
x_at_max_y 0.0                            
fwhm       3.0223874138499687             
variance   0.0                            
sigma      0.0                            
min_x      -3.0                           
mean_x     1.5                            
max_x      6.0                            
min_y      -0.09436187725503624           
mean_y     0.19753874119348702            
max_y      0.7724043891492777             
success    False                          
reasons    ['Computed peak sigma is zero.']
========== ================================
```

**Comment by prjemian** [comment]
To get the peak analysis into the dictionary on a routine basis, need to insert a call for that analysis before the call to `self.report()`: https://github.com/BCDA-APS/apstools/blob/bb907b99aac764e4f29c7ee2b8898024b821d85d/apstools/callbacks/scan_signal_statistics.py#L199-L205

How to keep `SignalStatsCallback` generic?

**Review by MDecarabas — APPROVED** [review]

**Comment by prjemian** [comment]
@MDecarabas  Thanks!

**Pull request merged**
