### PR TITLE
ENH: specify scan_id_source to RE as None

### PR DESCRIPTION
**Pull request by mrakitin**
This change is contingent on merging the corresponding Bluesky PR https://github.com/NSLS-II/bluesky/pull/1175, that's why creating it as a "Draft pull request" until after the Bluesky PR is merged.

### CODE REVIEW

**Comment by prjemian** [comment]
Hey!  Forgot to celebrate a birthday for this PR.  I'm not sure this is a problem since the `scan_id` is user metadata, even though it is managed by `bluesky`.  Not sure this is worth the bother.

**Comment by mrakitin** [comment]
Ha, yeah, took long time. I think we should reiterate in https://github.com/bluesky/bluesky/pull/1175.

**Comment by prjemian** [comment]
Per #430, I'd like to change the default branch name from `master` to `main` done by December 10 as part of the milestone for the 1.3.10 release.  You'll need to re-target this PR to point to the new branch, once that has been created.  Will proceed unless I hear comments.

**Review by prjemian — CHANGES_REQUESTED** [review]
In the [current `RunEngine` code](https://github.com/bluesky/bluesky/blob/fdc8a8a47b6ed292ee66715d22df2b15e6cd1966/bluesky/run_engine.py#L331), the `scan_id_source` kwarg defaults to a function call that assumes a dictionary has been provided as an argument.  We can't specify `None` here since any [use](https://github.com/bluesky/bluesky/blob/fdc8a8a47b6ed292ee66715d22df2b15e6cd1966/bluesky/run_engine.py#L1712) will fail with `TypeError: 'NoneType' object is not callable`.

**Comment by prjemian** [comment]
@mrakitin I'm inclined to close this PR as won't fix; the RE supplies an adequate default `scan_id` (`0`) now.

**Comment by prjemian** [comment]
@mrakitin Thanks.  Appears that bluesky/bluesky#1175 has stalled.  That idea is good and can be used not only with [`apstools.plans.snapshot()`](https://apstools.readthedocs.io/en/latest/source/_plans.html#apstools.plans.snapshot) but also with [`apstools.plans.documentation_run()`](https://apstools.readthedocs.io/en/latest/source/_plans.html#apstools._plans.doc_run.documentation_run).  The USAXS instrument uses this latter plan to record a table of samples when scanning a long batch.  Exceptionally useful to document **how** a long data acquisition session has been initiated.

**Pull request closed without merging**
