### PR TITLE
Make the home page friendlier

### LINKED ISSUE #955: Make the home page friendlier
Following https://github.com/BCDA-APS/bluesky_training/pull/289, lighten up the home page.

Looks like this now:

image

### LINKED ISSUE #957: Consider combining Overview and home pages.
Consider combining Overview and home pages.

_Originally posted by @prjemian in https://github.com/BCDA-APS/apstools/issues/956#issuecomment-2040341915_

### PR DESCRIPTION
**Pull request by prjemian**
- close #955
- close #957

### CODE REVIEW

**Comment by prjemian** [comment]
image

**Comment by prjemian** [comment]
Consider combining Overview and home pages.

**Comment by prjemian** [comment]
Ready for review.  Since the docs workflow does not upload a ZIP of the built docs (yet), I published to the development channel: https://bcda-aps.github.io/apstools/dev/index.html

**Comment by prjemian** [comment]
Now uploads docs built during workflow run.

**Comment by rodolakis** [comment]
That may be a bit stupid but the fact that Introduction does not follow the pattern of the other section confused me a bit: no introduction page, therefor section title not hyperlink and navigation bar does not quite match home page content.

**Comment by prjemian** [comment]
The Introduction card is odd.  Did not want to create a new intro page just for this simple content.  #957 will help, perhaps that should happen here?  Then, this card will be swapped out with content from the Overview page.

**Comment by prjemian** [comment]
@rodolakis How about this revision?

**Comment by prjemian** [comment]
Reviewed with @rodolakis this morning.

**Pull request merged**
